### ISSUE TITLE
Loosing WIFI connection

### ISSUE THREAD

**Issue by nightshift4000** [Lixie-Labs/Emotiscope#108]
Firmware used: 1.1

It seems the emotiscope looses WIFI connection over night. In the morning the LED in the bottom right corner is blinking. It is not able to auto-reconnect to the WIFI. I have waited at least an hour. Only power cycle helps.
No other WIFI device shows such issue (also ESP32 powered ones). WIFI signal strengh is high.

**Comment by connornishijima** [comment]
Very interesting. I made some changes to the Emotiscope app discovery server 2 days ago, has the connection problem risen again since?

**Comment by nightshift4000** [comment]
Hi. No, the last two days I did no recognize this.

**Comment by nightshift4000** [comment]
Quick update: This morning the WIFI connection was lost again. It was the first time since my last message. I soft-powered it off last night. This morning it was turned on for some reason and the LED was blinking (WIFI lost).

**Comment by connornishijima** [comment]
This has been resolved in the 2.0 rewrite, which is fully replacing both the software on Emotiscope (Arduino to ESPIDF) and the Web app (HTML5 to Godot). It's nearly complete but not yet officially released. I'll update this issue when 2.0 releases soon.
