### ISSUE TITLE
Animation freezing / Audio not detected

### ISSUE THREAD

**Issue by nightshift4000** [Lixie-Labs/Emotiscope#109]
Firmware used: 1.1

Sometimes the display is "freezing". It looks like the animation is paused. If that happens it also is not reacting on the touch input anymore. 
It might also happen that looks like the audio stream from the microphone is not processed anymore. Means, the display is still animated but it does not react on the room audio anymore. If that happens it might also enter the screensaver mode although there is audio in the room. I managed it to capture the effects on this video: [here](https://drive.google.com/file/d/16Dd7IuX0ksCtPRJ3FnSoGYoAutZUJSNj/view?usp=drive_link)
I did not noticed this with version 1.0 of the firmware (but I must admit that I did not use FW 1.0 that long, so I might have missed it)

**Comment by connornishijima** [comment]
This has been resolved in the 2.0 rewrite, which is fully replacing both the software on Emotiscope (Arduino to ESPIDF) and the Web app (HTML5 to Godot). It's nearly complete but not yet officially released. I'll update this issue when 2.0 releases soon.
