### ISSUE TITLE
Add mouse (desktop) support to web app

### ISSUE THREAD

**Issue by larryqiann** [Lixie-Labs/Emotiscope#77]
Hi, this is a quick hack, so maybe not super suitable for production use, but I made some quick edits to the files app.css, render_controls.js, and sliders.js to allow the web app to be used on a computer without a touch screen (By default, it's not possible to use the app at all, nothing responds to the mouse).

Horizontal scrolling is accomplished through always showing the scrollbar on the bottom, which isn't ideal but it's whats available. You can also horizontally scroll on your mouse if it supports this.

You can click and drag on the sliders to change their values, but I haven't gotten around to fixing the "toggle" mode, or the function where you can click on the Emotiscope device to turn it on and off.

Simply replace the files below, and/or add them as "overrides" in Chrome DevTools.

[override.zip](https://github.com/Lixie-Labs/Emotiscope/files/15050538/override.zip)

**Comment by connornishijima** [comment]
I've just pushed changes to the 1.1 branch that add official mouse input support, along with PC control and landscape mode. <3

Stay tuned for an OTA 1.1 update in the next week!
