### ISSUE TITLE
Add support for NUM_LEDS other than 128

### ISSUE THREAD

**Issue by larryqiann** [Lixie-Labs/Emotiscope#79]
[fix_background_longer_leds.patch](https://github.com/Lixie-Labs/Emotiscope/files/15053059/fix_background_longer_leds.patch)

Only tested on the 1.1 branch as of 79105ca currently but I don't think the files have changed much since 1.0. This patch solves [some of?] the problems with using Emotiscope with more or less than 128 LEDs as defined in leds.h/NUM_LEDS. 

The main issue previously was that the background wouldn't extend to the full strip in mirror mode in many of the modes (non-mirrored modes worked fine). These patches attempt to remove hard coded references to 63/64, which are the lengths of the hard-coded 128 LED strip.

**Comment by connornishijima** [comment]
Working on this today!

**Comment by connornishijima** [comment]
Fixed in https://github.com/Lixie-Labs/Emotiscope/commit/b9b981b88dc7a8ecdc27867b3e82eb2d7d26e187!
